-- Tabellen aanmaken in RAW schema

USE DATABASE CRIME_DB;
USE SCHEMA RAW;

CREATE TABLE IF NOT EXISTS CRIMINALITEIT_OBSERVATIONS (
    ID                                  INTEGER,
    SOORT_MISDRIJF                      VARCHAR(20),
    REGIO                               VARCHAR(20),
    PERIODE                             VARCHAR(20),
    TOTAAL_GEREGISTREERDE_MISDRIJVEN    FLOAT,
    GEREGISTREERDE_MISDRIJVEN_RELATIEF  FLOAT,
    GEREGISTREERDE_MISDRIJVEN_PER_1000  FLOAT,
    TOTAAL_OPGEHELDERDE_MISDRIJVEN      FLOAT,
    OPGEHELDERDE_MISDRIJVEN_RELATIEF    FLOAT,
    REGISTRATIES_VAN_VERDACHTEN         FLOAT
);

CREATE TABLE IF NOT EXISTS DIM_SOORT_MISDRIJF (
    KEY                VARCHAR(20),
    TITLE              VARCHAR(255),
    DESCRIPTION        VARCHAR(2000),
    CATEGORY_GROUP_ID  INTEGER
);

CREATE TABLE IF NOT EXISTS DIM_REGIO (
    KEY                VARCHAR(20),
    TITLE              VARCHAR(255),
    DESCRIPTION        VARCHAR(2000),
    CATEGORY_GROUP_ID  INTEGER
);

CREATE TABLE IF NOT EXISTS DIM_PERIODE (
    KEY     VARCHAR(20),
    TITLE   VARCHAR(20),
    DESCRIPTION VARCHAR(255),
    STATUS  VARCHAR(50)
);
